---
name: Tag Release
on:
  push:
    branches:
    - development
    paths:
    - ansible/configs/*/releases/*.txt
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@master
      fetch-depth: 2

    - name: Create tags
      id: get_version
      env:
        GIT_DEPLOY_KEY: "${{ secrets.GIT_DEPLOY_KEY }}"
      run: |
        tools/github-tag.sh
